import unittest
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep

class Meta_ua_login(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome(ChromeDriverManager().install())

    def test_login(self):
        self.driver.get("https://meta.ua/")
        sleep(2)
        self.driver.find_element_by_xpath('/html/body/div[2]/section/div[1]/span/a[1]/label').click()
        sleep(2)

        login = self.driver.find_element_by_xpath('//*[@id="login-form"]/div[2]/input[1]')
        login.send_keys('avsitidiiskyi12') # Keys module fills in the data
        sleep(2)
        password = self.driver.find_element_by_name('password')
        password.send_keys('Domination12')
        sleep(2)

        self.driver.find_element_by_xpath('//*[@id="login-form"]/button').click()

        sleep(2)
        self.driver.find_element_by_id('id_send_email').click()

        adress_field = self.driver.find_element_by_id('send_to')
        adress_field.send_keys('avsitidiiskyi@gmail.com')
        sleep(2)

        subject_field = self.driver.find_element_by_xpath('//*[@id="subject"]')
        subject_field.send_keys('Generated by Selenium Webdriver')
        sleep(2)

        body_field = self.driver.find_element_by_id('body')
        body_field.send_keys('This text has been composed and created automatically. \n Powered by Selenium Webdriver + Python. \nGovnocode belongs to Artem Avsitidiisky(c) ')
        sleep(2)

        self.driver.find_element_by_xpath('//*[@id="b3_cnt"]/div[2]/div[1]/div[1]/input[2]').click()

    def tearDown(self):
        self.driver.quit()

if __name__ == '__main__':





 #